const fs = require("fs");
const path = require("path");
const si = require("simple-icons");

const LOBE = "node_modules/@lobehub/icons-static-svg/icons";

/** Pulls the inner markup out of a lobehub SVG and namespaces every id, so
 *  three copies of the marquee cannot make one brand's gradient hijack
 *  another's. */
function fromLobe(file, slug) {
  const raw = fs.readFileSync(path.join(LOBE, file), "utf8");
  const viewBox = (raw.match(/viewBox="([^"]+)"/) || [, "0 0 24 24"])[1];
  let inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  inner = inner.replace(/<title>[\s\S]*?<\/title>/g, "");

  const ids = [...inner.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
  for (const id of new Set(ids)) {
    const safe = `${slug}-${id}`;
    inner = inner.split(`id="${id}"`).join(`id="${safe}"`);
    inner = inner.split(`url(#${id})`).join(`url(#${safe})`);
    inner = inner.split(`xlink:href="#${id}"`).join(`xlink:href="#${safe}"`);
  }
  return { viewBox, markup: inner.trim() };
}

function fromSimple(key, hex) {
  const icon = si[key];
  if (!icon) throw new Error(`missing simple-icon ${key}`);
  return {
    viewBox: "0 0 24 24",
    markup: `<path fill="${hex || "#" + icon.hex}" d="${icon.path}"/>`,
  };
}

// Ordered so the colourful AI marks and the familiar everyday apps alternate
// instead of clumping at one end of the strip.
const LIST = [
  ["ChatGPT", () => fromLobe("openai.svg", "openai"), "#0D0D0D"],
  ["Claude", () => fromLobe("claude-color.svg", "claude")],
  ["Notion", () => fromSimple("siNotion", "#0D0D0D")],
  ["Gemini", () => fromLobe("gemini-color.svg", "gemini")],
  ["Gmail", () => fromSimple("siGmail")],
  ["Grok", () => fromLobe("grok.svg", "grok"), "#0D0D0D"],
  ["Telegram", () => fromSimple("siTelegram")],
  ["Perplexity", () => fromLobe("perplexity-color.svg", "perplexity")],
  ["Figma", () => fromSimple("siFigma")],
  ["DeepSeek", () => fromLobe("deepseek-color.svg", "deepseek")],
  ["Obsidian", () => fromLobe("obsidian-color.svg", "obsidian")],
  // The colour version of Kimi is half white, which vanishes on a white chip;
  // the monochrome mark painted in the brand blue survives the light ground.
  ["Kimi", () => fromLobe("kimi.svg", "kimi"), "#1783FF"],
  ["Google", () => fromLobe("google-color.svg", "google")],
  ["Cursor", () => fromLobe("cursor.svg", "cursor"), "#0D0D0D"],
  ["Xcode", () => fromSimple("siXcode")],
  ["Linear", () => fromSimple("siLinear")],
  ["Discord", () => fromSimple("siDiscord")],
  ["WhatsApp", () => fromSimple("siWhatsapp")],
  ["Google Docs", () => fromSimple("siGoogledocs")],
  ["Safari", () => fromSimple("siSafari")],
];

const entries = LIST.map(([name, build, monoColour]) => {
  const { viewBox, markup } = build();
  return {
    name,
    viewBox,
    // Monochrome marks need a colour of their own; the lobehub ones paint with
    // currentColor, which would otherwise inherit the chip's text colour.
    colour: monoColour || null,
    markup,
  };
});

const file =
  `/** Brand marks: simple-icons (CC0) and @lobehub/icons-static-svg (MIT).\n` +
  ` *  Generated by scripts/gen-brands.js — edit that, not this file.\n` +
  ` *  Every id is namespaced per brand so repeated copies in the marquee\n` +
  ` *  cannot cross-reference each other's gradients.\n` +
  ` */\n` +
  `export type Brand = { name: string; viewBox: string; colour: string | null; markup: string };\n\n` +
  `export const BRANDS: Brand[] = ${JSON.stringify(entries, null, 2)};\n`;

fs.writeFileSync("lib/brands.ts", file);
console.log(`${entries.length} brands written`);
